### ISSUE TITLE
Entering password precedes entering username

### ISSUE THREAD

**Issue by afshar-mohammad** [hossein-1390/grading#2]
Not a fatal issue, but it would be nicer if the user enters username first.

- [tamrin.py](https://github.com/hossein-1390/grading/blob/755bbb4896f63cc22e669bca39dd7847ac506624/tamrin.py#L12)
- [student.py](https://github.com/hossein-1390/grading/blob/755bbb4896f63cc22e669bca39dd7847ac506624/student.py#L6)

**Comment by Ho3einMokhtari** [comment]
no problem
